service: dio-aws-desafio

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: us-east-1
  iam:
      role:
          statements:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:GetItem
                - dynamodb:Scan
              Resource:
                - arn:aws:dynamodb:us-east-1:167880115321:table/MinhaTabela
functions:
  hello:
    handler: src/hello.handler
    events:
      - http:
          path: /
          method: get
  adicionarItem:
    handler: src/adicionarItem.handler
    events:
      - http:
          path: /adicionarItem
          method: post    
  buscarTodosItems:
    handler: src/buscarTodosItems.handler
    events:
      - http:
          path: /buscarTodosItems
          method: get
  buscarPorId:
    handler: src/buscarPorId.handler
    events:
      - http:
          path: /buscarPorId/{id}
          method: get
  atualizarItem:
    handler: src/atualizarItem.handler
    events:
      - http:
          path: /atualizarItem/{id}
          method: put
resources:
  Resources:
    MinhaTabela:
      Type: AWS::DynamoDB::Table
      Properties:
          TableName: MinhaTabela
          BillingMode: PAY_PER_REQUEST
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH